# Welcome to Jekyll!
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Kita's Homepage
email: kitavoronok@gmail.com

description: >- # this means to ignore newlines until "baseurl:"
  Kita Voronok's personal homepage in the Internet. Шаипов Никита Геннадьевич, домашняя страница в Интернете.
baseurl: "" # the subpath of your site, e.g. /blog

domain: voronokkita.github.io # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com

url: https://voronokkita.github.io # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
destination: ./_result
sass:
  sass_dir: _sass
  load_paths:
    - _sass/error/
    - _sass/index/

encoding: "utf-8"

markdown: GFM

timezone: Europe/Moscow

ignore_theme_config: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
